### PR TITLE
Added new responsive charts and new color settings

### PR DESCRIPTION
**Pull request by josesaranda**
In this commit you can view a new example of how to use the new config variables **fillColor** and **responsive**.

Screen Recording 2019-08-08 at 03 02 27 13 PM

### CODE REVIEW

**Comment by domoritz** [comment]
I created two new issues to track these improvements. #144 and #145. It would be great to address them separately. 

Again, thank you for working on Falcon. It's great to have these improvements come in.

**Comment by josesaranda** [comment]
I think this support required a lot of effort. You can accept the PR for a minor version. (i.e: 0.14.4)
I would be very grateful

**Comment by domoritz** [comment]
Which one? Theming or responsive charts? 

Does your PR work with charts in multiple columns? It looks like every chart spans the whole width in your video.

**Comment by josesaranda** [comment]
Both. My PR works in multiple columns if you describe your container rewriting utils.ts createElement function and stylish the App.scss. Please see the example and try to change the layout. Then i will be grateful if you approve this PR.

**Comment by josesaranda** [comment]
Definitely i have used my fork repo and i have publish this feature in a new npm package called shapelets-falcon. I have recognized your authority and i keep the links to your main repo. Hope you like it.

Thanks you very much.

**Comment by domoritz** [comment]
Excellent. Thank you for sending the pull request! It's great to see that Falcon is being used and what things would make it better (theming and responsiveness). 

I'm going to close this PR but I will keep the issues that were inspired by this PR open.

**Pull request closed without merging**
